### ISSUE TITLE
LuckPerms not giving the prefix.

### ISSUE THREAD

**Issue by hardcorefactions** [Contrum/Rank-Implement#7]
LuckPerms  isn't giving the rank's prefix well. It just gives an empty string. I performed debugging with logging values. I'm using this:

String rankPrefix = rankManager.getRank().getRankPrefix(player.getUniqueId());

**Comment by coleedwards** [comment]
LuckPerms support seems to be working as intended with other customers, are you sure you've set a prefix for the `player`'s group?

getRankPrefix returns an empty string when the user's metadata for prefix is null.

**Comment by hardcorefactions** [comment]
yes, I'm using it with assemble's scoreboard API. I just fixed it using another way but now that I made more things for my Hub Core it just works. I must of not coded well.
